### ISSUE TITLE
Company Not Checked?

### ISSUE THREAD

**Issue by sprankhub** [netresearch/deutschepost-module-addressfactory-m2#1]
I am currently working on a Magento 1 ADDRESS FACTORY integration. I saw that you do not set the company in the request:

https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/1a26ac3d13dce81ccfd6c6fcc9a722d135e1fde2/Model/AddressAnalysis.php#L179-L195

Is there any specific reason for this? Has this been forgotten? I'd say the company is an important part of many addresses, so I really do not get why it is missing here :thinking:

**Comment by powli** [comment]
Hey @sprankhub,
 From what I gather from the PostDirekt Addressfactory handbook, the underlying database is focused on private persons and not really considering companies in the same building. The company field, therefore, seems to have a relatively low influence on the address results.

**Comment by sprankhub** [comment]
At least there are specific files for company addresses, so I am not sure if this is private-persons-only. At least I do not see any harm in adding the company. If we send more data, DP should be able to validate better. Do you see any disadvantage?

**Comment by powli** [comment]
I don't see any possible harm done by properly sending the company field forward
