### ISSUE TITLE
Support For Packing Stations

### ISSUE THREAD

**Issue by sprankhub** [netresearch/deutschepost-module-addressfactory-m2#3]
As discussed in https://github.com/netresearch/deutschepost-sdk-addressfactory/issues/1, I think this module should also care about packing stations. If the customer uses the official location finder functionality, validation is probably not an issue. However, in my experience, many clients / customers do not use it and enter the data manually. And in this case, a validation is very helpful.

**Comment by powli** [comment]
We are currently in discussions with Deutsche Post Direkt on the details of the implementation and feature scope regarding packing stations, so stay tuned.

**Comment by powli** [comment]
Implemented since [1.2.0](https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/CHANGELOG.md#120)
