### ISSUE TITLE
Empty Address When Used with Packing Stations

### ISSUE THREAD

**Issue by sprankhub** [netresearch/deutschepost-module-addressfactory-m2#4]
To be honest, I could not test this, because I do not have access to this in M2 currently. However, based on the code, I think there is an issue with packing station addresses:

1. Order something and use a valid packing station and post number as the shipping address.
2. Let the module auto-correct addresses and let the module run validation on the newly created order.

Expected behaviour: Nothing changes, because [packing stations are currently not supported](https://github.com/netresearch/deutschepost-module-addressfactory-m2/issues/3).
Actual behaviour: The address fields are emptied, because the module "blindly" uses the address suggested by DP. And since the DP validation service detects the address as a packing station address, the response will not include the address data in the default address fields, but in packing-station-specific fields, which are currently [not returned by the underlying SDK](https://github.com/netresearch/deutschepost-sdk-addressfactory/issues/1).

Would you mind verifying this in your test systems?

**Comment by powli** [comment]
Packing stations are supported since [1.2.0](https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/CHANGELOG.md#120)
