### ISSUE TITLE
Orders not marked as pending for address-validation

### ISSUE THREAD

**Issue by berwa** [netresearch/deutschepost-module-addressfactory-m2#6]
Hello Netresearch-team,
We could not get the cron-based validation working without a certain modification, but were unsure if we might miss something:

In https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/c1e27accf4ebc31895fefa5dca33b69430044dad/Observer/SetNewOrderDeliverabilityStatus.php#L73 the validation of `!$address->isObjectNew()` is performed, which always came back `true` in our tests and resulted in the order not being marked as pending for address-validation and thus not being validated at all.

At the end `isObjectNew` only checks whether an id was already assigned to the object (https://github.com/magento/magento2/blob/0e33b801d664b1a09bbe45456d09db0ca1ec10e6/lib/internal/Magento/Framework/Model/AbstractModel.php#L689). 
But as this check is performed during the `sales_order_address_save_after` event our conclusion is that the address was already saved to the database and thus got an id assigned.

This is why we changed the validation from
`if ((!$address || !$address->isObjectNew()) )`
to
`if (!$address)`

Additional information: we are using the module with Adobe Commerce 2.4.6-p2.

**Comment by powli** [comment]
Hello @berwa,

thanks for the report, we will investigate the issue and provide a fix if it is a bug.

_Internal ref: PDTWO-200_

**Comment by mam08ixo** [comment]
Thank you for reporting the issue, fixed in version [1.4.2](https://github.com/netresearch/deutschepost-module-addressfactory-m2/releases/tag/1.4.2).
