### ISSUE TITLE
Saving the whole collection instead of adding items

### ISSUE THREAD

**Issue by AndreyKV777** [netresearch/deutschepost-module-addressfactory-m2#7]
Here is saveList() in line [122](https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/Model/AddressAnalysis.php#L122) .
It saves all the collection just to add some new records. In the case of a real database, it can be thousands of records which sometimes leads to a timeout on the address validation in the Magento admin.

**Comment by powli** [comment]
@AndreyKV777 thank you for the feedback. 

The `saveList` function is our own implementation (see [here](https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/Model/AnalysisResultRepository.php#L128-L140)) and does only save the new results to the database, not the whole collection.

**Comment by AndreyKV777** [comment]
@powli Hi.
yes,  inside saveList is  $searchResult->save();
where searchResult is a collection: 
SELECT `main_table`.* FROM `postdirekt_addressfactory_analysis` AS `main_table`
$searchResult->save() calls 
 Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection::save
where all the elements are saved in a loop..
I guess, a loop of $newAnalysisResults: $this->analysisResultRepository->save($newAnalysisResult) instead of saveList would be more optimal

**Comment by poebel** [comment]
@powli 

> and does only save the new results to the database, not the whole collection.

That's unfortunately not true, it loads and saves _all_ entries in the `postdirekt_addressfactory_analysis` table.

Your call to `setItems()` on the search result / collection does NOT set the `$_isCollectionLoaded` flag to true.

Therefore the call to the `->save()` method which internally calls `->getItems()` which then calls `->load()` loads the whole collection without any filters, leading to every entry being saved again.

**Comment by powli** [comment]
@poebel Thanks for the pointer, I missed that.

Wouldn't adding a `$this->_setisLoaded()` [here](https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/Model/ResourceModel/AnalysisResult/SearchResult.php#L88) also solve the issue? I'd prefer that.

**Comment by poebel** [comment]
@powli 
That would most likely work, but I have some more general issues with that approach:

1. You wil again use a `\Magento\Framework\Api\SearchResultsInterface` in a write context.
I'd usually not expect a `SearchResultsInterface` being used for writing altough in your case you've decided to implement it as an extension of `\Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection` which allows such usage.
There is a reason most implementations in the core do not do this and extend `\Magento\Framework\Api\SearchResults` instead.
2. Even if the `AbstractCollection` allows write operations it is usually not used to create new entities.
Generally it's used to read and sometimes manipulate and save _existing_ entities.
Manually manipulating the items of a database collection is from my experience a good way to cause issues down the road.
You have for example no checks in your `->setItems()` method in place to validate if your items are unique (= have an unique id), which is fine and sometimes even intended for a `SearchResultsInterface` but will cause issues due the unique checks in the `->addItem()` method of the collection.
